export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "secondary": "#c6c6c7",
              "outline-variant": "#584140",
              "on-primary-fixed": "#410006",
              "secondary-container": "#454747",
              "tertiary-fixed-dim": "#4cd6ff",
              "surface-bright": "#3a3939",
              "on-error-container": "#ffdad6",
              "on-tertiary": "#003543",
              "primary-container": "#ff6b6b",
              "on-secondary-fixed-variant": "#454747",
              "on-secondary-fixed": "#1a1c1c",
              "surface-container-highest": "#353534",
              "on-surface-variant": "#e0bfbd",
              "outline": "#a78a88",
              "surface-variant": "#353534",
              "inverse-on-surface": "#313030",
              "surface-container-lowest": "#0e0e0e",
              "on-tertiary-fixed": "#001f28",
              "error-container": "#93000a",
              "tertiary-container": "#00a9cf",
              "surface-dim": "#131313",
              "tertiary-fixed": "#b7eaff",
              "primary-fixed-dim": "#ffb3b0",
              "on-primary-fixed-variant": "#8c1520",
              "on-secondary": "#2f3131",
              "on-background": "#e5e2e1",
              "secondary-fixed": "#e2e2e2",
              "on-primary": "#68000f",
              "tertiary": "#4cd6ff",
              "on-secondary-container": "#b4b5b5",
              "on-tertiary-container": "#003847",
              "error": "#ffb4ab",
              "surface-container-high": "#2a2a2a",
              "primary-fixed": "#ffdad8",
              "on-tertiary-fixed-variant": "#004e60",
              "on-primary-container": "#6d0010",
              "surface-container": "#201f1f",
              "on-surface": "#e5e2e1",
              "on-error": "#690005",
              "inverse-surface": "#e5e2e1",
              "surface-tint": "#ffb3b0",
              "surface-container-low": "#1c1b1b",
              "surface": "#131313",
              "primary": "#ffb3b0",
              "secondary-fixed-dim": "#c6c6c7",
              "background": "#131313",
              "inverse-primary": "#ae2f34"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "9999px"
          },
          "fontFamily": {
              "headline": ["Newsreader", "serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
          }
      },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
}
